name = "xiaodouliwebsite"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Assets configuration - serve built React app
[assets]
directory = "./dist"

# 如果你有自定义域名，可以添加路由配置
# routes = [
#   { pattern = "yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# 如果你有自定义域名，取消下面的注释并修改
# [env.production]
# routes = [
#   { pattern = "your-domain.com/*", zone_name = "your-domain.com" }
# ]

# 环境变量（如果需要的话）
# [vars]
# ENVIRONMENT = "production"
